# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-26 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Addon', max_length=40)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('style_id', models.IntegerField()),
                ('brand', models.CharField(default='Default Brand', max_length=100)),
                ('name', models.CharField(default='Default Style', max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='StyleColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Default Color', max_length=40)),
                ('slug', models.SlugField(default='default-color', editable=False, max_length=40)),
                ('hex', models.CharField(default='FFFFFF', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StyleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.URLField(blank=True, null=True)),
                ('back', models.URLField(blank=True, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.StyleColor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
        ),
        migrations.CreateModel(
            name='StylePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price4', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price5', models.DecimalField(decimal_places=2, max_digits=6)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Style')),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='colors',
            field=models.ManyToManyField(to='api.StyleColor'),
        ),
    ]
