# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180820_0646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InkColor',
        ),
    ]
